version: 2
registries:
  xflash-panda-git:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.XFLASH_PANDA_REPO_TOKEN }}

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    registries:
      - xflash-panda-git
    schedule:
      interval: "weekly"
    target-branch: "dev/master"
